In [1]:
ls

 Volume in drive E is 学校资料资源教学
 Volume Serial Number is 5ADC-AF84

 Directory of E:\tsl_file\python_project\gene\geatpy_example\frame\schedule_new\boat_data

2021/06/05  15:09    <DIR>          .
2021/06/05  15:09    <DIR>          ..
2021/06/05  15:09    <DIR>          .ipynb_checkpoints
2021/06/05  15:06            12,712 529.xlsx
2021/06/05  15:05            12,819 604.xlsx
2021/06/05  15:09                72 data_process.ipynb
               3 File(s)         25,603 bytes
               3 Dir(s)  109,210,873,856 bytes free

In [1]:
data_529_path='529.xlsx'
# data_604_path='604.xlsx'
data_530_path='530.xlsx'
data_531_path='531.xlsx'
data_path='total.xlsx'
data_path='scheduled_total.xlsx'
data_path='scheduled_total_split.xlsx'

In [2]:
import pandas as pd
import re

In [243]:
data_529=pd.read_excel(data_529_path,header=None)
data_530=pd.read_excel(data_530_path,header=None)
data_531=pd.read_excel(data_531_path,header=None)
data1=pd.read_excel(data_path,header=None,sheet_name='Sheet1')
data2=pd.read_excel(data_path,header=None,sheet_name='Sheet2')
data3=pd.read_excel(data_path,header=None,sheet_name='Sheet3')

In [3]:
dd=pd.read_excel(data_path,header=None,sheet_name=None)

In [4]:
dd.keys()

dict_keys(['Sheet1', 'Sheet2', 'Sheet3'])

In [8]:
for sheet_name,e_df in dd.items():
    print(sheet_name,e_df)

Sheet1            0              1
0      荣江019  110.00, 19.25
1   新长江06072  110.00, 19.24
2   豫信货16899      99.0，16.0
3      洋河998   99.80, 16.25
4        渝扬2  106.00, 17.28
5       圣通19  110.00, 19.25
6     宏声3105   87.00, 14.83
7     金甲5198     105.0，16.0
8   豫信货15278   79.60, 13.60
9   豫信货17118     105.0，17.0
10     江运916  110.00, 19.20
11    旺洲2001  110.00, 19.28
12     镔港817  109.70, 16.24
13    龙昊2021     130.0，16.0
14       油源6   87.30, 13.23
15     秭归819   83.00, 13.84
16     天畅906   84.90, 14.03
17    曙光9888   90.45, 14.83
18  豫信货16986      79.0，13.0
19     石宝819      80.0，13.0
20    神州2016      87.0，15.0
21    远洋7001  105.02, 16.23
22     欣陇668   80.00, 13.22
23     民福666   78.00, 13.64
24      鸿海11   76.70, 12.00
25     龙昊916  109.80, 19.25
26  豫信货17598      92.0，16.0
27    亲河1028  129.97, 16.24
28      江润玖玖   92.00, 16.23
29      江渝玖玖  105.00, 17.20
30     金运868   92.00, 14.83
31     中来998   92.00, 14.80
32  豫鑫裕13686   79.60, 13.62
33  豫信货15006  105.00, 16.20
34   重轮化2008   87.00, 14.82
35   新平江1003   87.00, 13.62
36    麒麟皓166      78.0，14.0
37      祥牛12     107.0，14.0
38    弘茂1096     108.0，17.0
39    秭归1000   87.80, 14.63
40     恒驰629     130.0，16.0
41    东运1001   99.80, 16.24
42     隆盛918     105.0，16.0
43      兴晟02  105.00, 16.25
44      茂达3号  108.00, 17.25
45    海鸿6666   99.80, 16.23
46     腾龙189   94.80, 16.23
47     锦龙252   85.00, 14.83
48     巨能818   86.48, 14.24
49      国平9号   89.80, 16.04
50     生祥918   86.48, 14.24
51        民昊  110.00, 17.20
52      河牛82  129.90, 16.25
53     神帆803      80.0，14.0
54    宜昌民信1号   86.80, 14.24
55  豫信货15619   79.60, 13.60
56     杨帆666   64.90, 11.50
Sheet2           0              1
0   江海洋2016   92.00, 16.20
1     航万968  104.98, 16.23
2     灏泽001  105.00, 16.23
3    长兴1668  129.98, 16.26
4     镔港968  108.00, 17.25
..      ...            ...
57     富发88   93.82, 16.20
58   弘茂6666      80.0,14.0
59  豫周江河610      80.0，14.0
60    航发898   80.00, 13.63
61      鹏杰5   80.00, 13.63

[62 rows x 2 columns]
Sheet3            0              1
0   豫信货17788     110.0,17.0
1       飞艳18   92.00, 14.83
2      吉耘918   99.80, 16.25
3     港盛1618  108.00, 17.25
4      长荣998     110.0，17.0
..       ...            ...
66     宏青818      86.0,14.0
67     云浩918   74.30, 13.64
68     民联908   99.60, 16.24
69       永通6      87.0,14.0
70     千千988   99.60, 16.23

[71 rows x 2 columns]

In [6]:
dd['Sheet1']

           0              1
0      荣江019  110.00, 19.25
1   新长江06072  110.00, 19.24
2   豫信货16899      99.0，16.0
3      洋河998   99.80, 16.25
4        渝扬2  106.00, 17.28
5       圣通19  110.00, 19.25
6     宏声3105   87.00, 14.83
7     金甲5198     105.0，16.0
8   豫信货15278   79.60, 13.60
9   豫信货17118     105.0，17.0
10     江运916  110.00, 19.20
11    旺洲2001  110.00, 19.28
12     镔港817  109.70, 16.24
13    龙昊2021     130.0，16.0
14       油源6   87.30, 13.23
15     秭归819   83.00, 13.84
16     天畅906   84.90, 14.03
17    曙光9888   90.45, 14.83
18  豫信货16986      79.0，13.0
19     石宝819      80.0，13.0
20    神州2016      87.0，15.0
21    远洋7001  105.02, 16.23
22     欣陇668   80.00, 13.22
23     民福666   78.00, 13.64
24      鸿海11   76.70, 12.00
25     龙昊916  109.80, 19.25
26  豫信货17598      92.0，16.0
27    亲河1028  129.97, 16.24
28      江润玖玖   92.00, 16.23
29      江渝玖玖  105.00, 17.20
30     金运868   92.00, 14.83
31     中来998   92.00, 14.80
32  豫鑫裕13686   79.60, 13.62
33  豫信货15006  105.00, 16.20
34   重轮化2008   87.00, 14.82
35   新平江1003   87.00, 13.62
36    麒麟皓166      78.0，14.0
37      祥牛12     107.0，14.0
38    弘茂1096     108.0，17.0
39    秭归1000   87.80, 14.63
40     恒驰629     130.0，16.0
41    东运1001   99.80, 16.24
42     隆盛918     105.0，16.0
43      兴晟02  105.00, 16.25
44      茂达3号  108.00, 17.25
45    海鸿6666   99.80, 16.23
46     腾龙189   94.80, 16.23
47     锦龙252   85.00, 14.83
48     巨能818   86.48, 14.24
49      国平9号   89.80, 16.04
50     生祥918   86.48, 14.24
51        民昊  110.00, 17.20
52      河牛82  129.90, 16.25
53     神帆803      80.0，14.0
54    宜昌民信1号   86.80, 14.24
55  豫信货15619   79.60, 13.60
56     杨帆666   64.90, 11.50

In [337]:
data=data3

In [338]:
# data_604=pd.read_excel(data_604_path,header=None)

In [339]:
# data_529.head()

In [6]:
def process_data(row):
    L_W=re.split('[,，]',row)
#     print(row,L_W)
    L,W=    L_W
    return pd.Series([L,W])

In [341]:
# df=data_529.append(data_530)
# df=df.append(data_530)

In [342]:
# df.shape

In [343]:
data.shape

(71, 2)

In [344]:
data.drop_duplicates().shape

(71, 2)

In [345]:
# df.drop_duplicates().shape

In [346]:
# df.head()

In [347]:
data.head()

          0              1
0  豫信货17788     110.0,17.0
1      飞艳18   92.00, 14.83
2     吉耘918   99.80, 16.25
3    港盛1618  108.00, 17.25
4     长荣998     110.0，17.0

In [348]:
df=data[[0,1]]

In [349]:
df.head()

          0              1
0  豫信货17788     110.0,17.0
1      飞艳18   92.00, 14.83
2     吉耘918   99.80, 16.25
3    港盛1618  108.00, 17.25
4     长荣998     110.0，17.0

In [350]:
df=df.rename(columns={0:'boat_name'})

In [351]:
df.head()

  boat_name              1
0  豫信货17788     110.0,17.0
1      飞艳18   92.00, 14.83
2     吉耘918   99.80, 16.25
3    港盛1618  108.00, 17.25
4     长荣998     110.0，17.0

In [352]:
df.shape

(71, 2)

In [353]:
df[['L','W']]=df[1].apply(lambda x:process_data(x))

In [354]:
df.head()

  boat_name              1       L       W
0  豫信货17788     110.0,17.0   110.0    17.0
1      飞艳18   92.00, 14.83   92.00   14.83
2     吉耘918   99.80, 16.25   99.80   16.25
3    港盛1618  108.00, 17.25  108.00   17.25
4     长荣998     110.0，17.0   110.0    17.0

In [355]:
L=df['L']
W=df['W']
boat_name=df['boat_name']
ind=list(df.index)

In [356]:
L,W

(0      110.0
 1      92.00
 2      99.80
 3     108.00
 4      110.0
        ...
 66      86.0
 67     74.30
 68     99.60
 69      87.0
 70     99.60
 Name: L, Length: 71, dtype: object, 0       17.0
 1      14.83
 2      16.25
 3      17.25
 4       17.0
        ...
 66      14.0
 67     13.64
 68     16.24
 69      14.0
 70     16.23
 Name: W, Length: 71, dtype: object)

In [357]:
boat_name

0     豫信货17788
1         飞艳18
2        吉耘918
3       港盛1618
4        长荣998
        ...
66       宏青818
67       云浩918
68       民联908
69         永通6
70       千千988
Name: boat_name, Length: 71, dtype: object

In [358]:
ind

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70]

In [359]:
ind_name={i:n for i,n in zip(ind,boat_name)}

In [360]:
ind_name

{0: '豫信货17788',
 1: '飞艳18',
 2: '吉耘918',
 3: '港盛1618',
 4: '长荣998',
 5: '海辉307',
 6: '国祥898',
 7: '渝扬6',
 8: '渝山988',
 9: '和海66',
 10: '新平江1009',
 11: '豫信货17799',
 12: '云浩818',
 13: '海牛69',
 14: '镔港808',
 15: '平洋898',
 16: '乔泰26',
 17: '砚海998',
 18: '帝豪8',
 19: '祥牛6',
 20: '川北988',
 21: '曙光668',
 22: '新宜超越',
 23: '航兴901',
 24: '长安69',
 25: '兴晟05',
 26: '云隆88',
 27: '新平江3005',
 28: '盛畅8198',
 29: '领航飞翔',
 30: '龙昊1005',
 31: '九五888',
 32: '天龙贰号',
 33: '金海168',
 34: '豫宛货2077',
 35: '宏源819',
 36: '聚龙988',
 37: '长兴1868',
 38: '云浩999',
 39: '宏河918',
 40: '宜昌金航66',
 41: '航平906',
 42: '金河18',
 43: '新平江3003',
 44: '新平江1028',
 45: '宜都广翼196',
 46: '江韵1008',
 47: '恒洋18',
 48: '天畅908',
 49: '浦航998',
 50: '龙腾819',
 51: '鹏杰8',
 52: '宜化6号',
 53: '江集运1212',
 54: '浩航1009',
 55: '长航集运0335',
 56: '林瑞9',
 57: '长兴1015',
 58: '裕汇21508',
 59: '远洋9210',
 60: '鄂石2176',
 61: '豫信货13986',
 62: '曙光888',
 63: '海牛1009',
 64: '民超',
 65: '江泓898',
 66: '宏青818',
 67: '云浩918',
 68: '民联908',
 69: '永通6',
 70: '千千988'}

In [361]:
wait_list=[[float(l),float(w)] for l,w, in zip(L,W)]

In [362]:
print(wait_list)

[[110.0, 17.0], [92.0, 14.83], [99.8, 16.25], [108.0, 17.25], [110.0, 17.0], [110.0, 18.0], [110.0, 19.25], [106.0, 17.25], [106.8, 16.25], [95.0, 16.23], [87.0, 13.6], [110.0, 17.0], [75.7, 13.12], [130.0, 16.0], [110.0, 17.2], [105.0, 17.2], [110.0, 19.2], [92.0, 14.83], [99.9, 16.24], [99.8, 16.3], [86.48, 14.24], [85.32, 14.16], [79.0, 13.0], [86.8, 16.23], [82.0, 14.04], [99.8, 16.25], [85.0, 14.03], [87.0, 14.8], [79.6, 13.63], [79.8, 13.6], [129.97, 16.2], [92.0, 14.85], [86.0, 14.0], [108.0, 17.2], [79.6, 13.6], [99.8, 16.21], [88.0, 14.0], [129.98, 16.26], [87.0, 14.0], [99.8, 16.25], [100.0, 16.0], [105.0, 16.0], [65.5, 10.83], [87.0, 14.83], [87.0, 13.62], [78.0, 13.63], [79.6, 13.62], [130.0, 16.0], [90.8, 14.84], [99.8, 16.24], [90.0, 15.0], [105.0, 16.0], [82.0, 14.0], [105.0, 17.24], [110.0, 16.0], [107.0, 17.24], [105.0, 16.0], [104.81, 16.23], [110.0, 19.2], [100.0, 17.2], [86.8, 14.83], [105.0, 16.24], [79.58, 13.8], [129.92, 16.24], [107.0, 17.24], [99.8, 16.25], [86.0, 14.0], [74.3, 13.64], [99.6, 16.24], [87.0, 14.0], [99.6, 16.23]]

In [363]:

##把运行结果复制过来
# all_brake_boat ={0: {'brake_boat': {121: [(0, 0), (92.0, 16.0)], 25: [(0, 16.0), (130.0, 16.0)], 127: [(92.0, 0), (80.0, 14.0)], 29: [(130.0, 16.0), (130.0, 16.0)], 34: [(172.0, 0), (92.0, 16.0)]}, 'best_use_rate': 0.8638655462184874}, 1: {'brake_boat': {32: [(0, 0), (130.0, 16.0)], 85: [(0, 16.0), (98.0, 16.0)], 64: [(98.0, 16.0), (79.0, 14.0)], 23: [(130.0, 0), (130.0, 16.0)], 61: [(177.0, 16.0), (87.0, 14.0)]}, 'best_use_rate': 0.8457983193277311}, 2: {'brake_boat': {26: [(0, 0), (130.0, 16.0)], 86: [(0, 16.0), (92.0, 16.0)], 46: [(92.0, 16.0), (80.0, 14.0)], 31: [(130.0, 0), (130.0, 16.0)], 124: [(172.0, 16.0), (90.0, 15.0)]}, 'best_use_rate': 0.8510504201680672}, 3: {'brake_boat': {21: [(0, 0), (130.0, 16.0)], 33: [(0, 16.0), (92.0, 15.0)], 119: [(92.0, 16.0), (80.0, 14.0)], 28: [(130.0, 0), (130.0, 16.0)], 94: [(172.0, 16.0), (90.0, 16.0)]}, 'best_use_rate': 0.8508403361344538}, 4: {'brake_boat': {78: [(0, 0), (103.0, 16.0)], 20: [(0, 16.0), (105.0, 16.0)], 133: [(103.0, 0), (61.0, 14.0)], 27: [(105.0, 16.0), (130.0, 16.0)], 81: [(164.0, 0), (100.0, 16.0)]}, 'best_use_rate': 0.8258403361344537}, 5: {'brake_boat': {123: [(0, 0), (91.0, 15.0)], 108: [(0, 15.0), (86.0, 14.0)], 98: [(86.0, 15.0), (87.0, 17.0)], 56: [(91.0, 0), (80.0, 14.0)], 66: [(171.0, 0), (92.0, 15.0)], 102: [(173.0, 15.0), (86.0, 16.0)]}, 'best_use_rate': 0.8323529411764706}, 6: {'brake_boat': {101: [(0, 0), (92.0, 15.0)], 1: [(0, 15.0), (110.0, 17.0)], 114: [(92.0, 0), (80.0, 14.0)], 22: [(110.0, 15.0), (130.0, 16.0)], 92: [(172.0, 0), (86.0, 15.0)]}, 'best_use_rate': 0.8130252100840336}, 7: {'brake_boat': {14: [(0, 0), (90.0, 16.0)], 43: [(0, 16.0), (79.0, 13.0)], 80: [(79.0, 16.0), (100.0, 16.0)], 42: [(90.0, 0), (87.0, 14.0)], 17: [(177.0, 0), (87.0, 15.0)], 5: [(179.0, 16.0), (85.0, 14.0)]}, 'best_use_rate': 0.8172268907563025}, 8: {'brake_boat': {83: [(0, 0), (105.0, 16.0)], 105: [(0, 16.0), (92.0, 16.0)], 37: [(92.0, 16.0), (83.0, 14.0)], 24: [(105.0, 0), (130.0, 16.0)], 11: [(175.0, 16.0), (87.0, 15.0)]}, 'best_use_rate': 0.808718487394958}, 9: {'brake_boat': {90: [(0, 0), (87.0, 15.0)], 30: [(0, 15.0), (130.0, 16.0)], 18: [(87.0, 0), (87.0, 15.0)], 73: [(130.0, 15.0), (108.0, 17.0)], 99: [(174.0, 0), (90.0, 15.0)]}, 'best_use_rate': 0.8273109243697478}, 10: {'brake_boat': {107: [(0, 0), (80.0, 15.0)], 57: [(0, 15.0), (57.0, 10.0)], 69: [(57.0, 15.0), (105.0, 17.0)], 75: [(80.0, 0), (78.0, 14.0)], 15: [(162.0, 15.0), (100.0, 17.0)], 54: [(158.0, 0), (92.0, 15.0)]}, 'best_use_rate': 0.8116596638655462}, 11: {'brake_boat': {41: [(0, 0), (99.0, 16.0)], 71: [(0, 16.0), (80.0, 14.0)], 44: [(80.0, 16.0), (85.0, 15.0)], 72: [(99.0, 0), (65.0, 12.0)], 134: [(164.0, 0), (100.0, 16.0)], 110: [(165.0, 16.0), (84.0, 14.0)]}, 'best_use_rate': 0.7914915966386554}, 12: {'brake_boat': {10: [(0, 0), (87.0, 14.0)], 130: [(0, 14.0), (106.0, 17.0)], 122: [(87.0, 0), (80.0, 14.0)], 4: [(106.0, 14.0), (116.0, 18.0)], 53: [(167.0, 0), (92.0, 14.0)]}, 'best_use_rate': 0.7894957983193277}, 13: {'brake_boat': {35: [(0, 0), (92.0, 16.0)], 96: [(0, 16.0), (90.0, 15.0)], 9: [(90.0, 16.0), (87.0, 14.0)], 55: [(92.0, 0), (78.0, 14.0)], 117: [(170.0, 0), (94.0, 16.0)], 47: [(177.0, 16.0), (80.0, 14.0)]}, 'best_use_rate': 0.8147058823529412}, 14: {'brake_boat': {12: [(0, 0), (87.0, 14.0)], 131: [(0, 14.0), (108.0, 17.0)], 68: [(108.0, 14.0), (108.0, 17.0)], 74: [(87.0, 0), (90.0, 14.0)], 79: [(177.0, 0), (86.0, 14.0)]}, 'best_use_rate': 0.7724789915966387}, 15: {'brake_boat': {84: [(0, 0), (100.0, 16.0)], 113: [(0, 16.0), (100.0, 16.0)], 89: [(100.0, 0), (77.0, 13.0)], 118: [(100.0, 13.0), (110.0, 19.0)], 58: [(177.0, 0), (80.0, 13.0)]}, 'best_use_rate': 0.7700630252100841}, 16: {'brake_boat': {0: [(0, 0), (110.0, 16.0)], 87: [(0, 16.0), (80.0, 14.0)], 65: [(80.0, 16.0), (99.0, 16.0)], 60: [(110.0, 0), (105.0, 16.0)], 106: [(179.0, 16.0), (85.0, 14.0)]}, 'best_use_rate': 0.7703781512605042}, 17: {'brake_boat': {48: [(0, 0), (79.0, 13.0)], 112: [(0, 13.0), (110.0, 19.0)], 38: [(110.0, 13.0), (110.0, 19.0)], 93: [(79.0, 0), (80.0, 13.0)], 103: [(159.0, 0), (79.0, 13.0)]}, 'best_use_rate': 0.7640756302521008}, 18: {'brake_boat': {125: [(0, 0), (86.0, 14.0)], 63: [(0, 14.0), (106.0, 18.0)], 8: [(86.0, 0), (87.0, 14.0)], 6: [(106.0, 14.0), (100.0, 17.0)], 13: [(173.0, 0), (86.0, 14.0)]}, 'best_use_rate': 0.7598739495798319}, 19: {'brake_boat': {91: [(0, 0), (105.0, 16.0)], 51: [(0, 16.0), (105.0, 16.0)], 67: [(105.0, 0), (107.0, 14.0)], 120: [(105.0, 14.0), (110.0, 17.0)]}, 'best_use_rate': 0.7067226890756303}, 20: {'brake_boat': {132: [(0, 0), (105.0, 16.0)], 19: [(0, 16.0), (105.0, 16.0)], 95: [(105.0, 0), (102.0, 16.0)], 3: [(105.0, 16.0), (105.0, 16.0)]}, 'best_use_rate': 0.7008403361344537}, 21: {'brake_boat': {109: [(0, 0), (100.0, 16.0)], 88: [(0, 16.0), (105.0, 16.0)], 97: [(100.0, 0), (100.0, 16.0)], 115: [(105.0, 16.0), (100.0, 16.0)]}, 'best_use_rate': 0.680672268907563}, 22: {'brake_boat': {77: [(0, 0), (99.0, 16.0)], 40: [(0, 16.0), (99.0, 16.0)], 49: [(99.0, 0), (80.0, 13.0)], 62: [(99.0, 13.0), (110.0, 19.0)]}, 'best_use_rate': 0.6615546218487395}, 23: {'brake_boat': {70: [(0, 0), (111.0, 20.0)], 45: [(111.0, 0), (88.0, 14.0)], 104: [(111.0, 14.0), (108.0, 17.0)]}, 'best_use_rate': 0.5554621848739496}, 24: {'brake_boat': {36: [(0, 0), (110.0, 19.0)], 76: [(110.0, 0), (110.0, 19.0)]}, 'best_use_rate': 0.43907563025210083}, 25: {'brake_boat': {111: [(0, 0), (110.0, 19.0)], 128: [(110.0, 0), (110.0, 19.0)]}, 'best_use_rate': 0.43907563025210083}, 26: {'brake_boat': {126: [(0, 0), (110.0, 19.0)], 116: [(110.0, 0), (110.0, 19.0)]}, 'best_use_rate': 0.43907563025210083}, 27: {'brake_boat': {39: [(0, 0), (110.0, 19.0)], 100: [(110.0, 0), (110.0, 19.0)]}, 'best_use_rate': 0.43907563025210083}, 28: {'brake_boat': {129: [(0, 0), (106.0, 17.0)], 50: [(106.0, 0), (105.0, 17.0)]}, 'best_use_rate': 0.3767857142857143}, 29: {'brake_boat': {59: [(0, 0), (105.0, 17.0)], 2: [(105.0, 0), (105.0, 17.0)]}, 'best_use_rate': 0.375}, 30: {'brake_boat': {16: [(0, 0), (100.0, 17.0)], 82: [(100.0, 0), (100.0, 17.0)]}, 'best_use_rate': 0.35714285714285715}, 31: {'brake_boat': {52: [(0, 0), (100.0, 17.0)], 7: [(100.0, 0), (98.0, 17.0)]}, 'best_use_rate': 0.3535714285714286}}

# all_brake_boat ={0: {'brake_boat': {244: [(0, 0), (129.98, 16.26)], 39: [(0, 16.26), (129.98, 16.26)], 53: [(129.98, 0), (129.9, 16.25)], 57: [(129.98, 16.25), (130.0, 16.0)]}, 'best_use_rate': 0.8842252731092437}, 1: {'brake_boat': {178: [(0, 0), (88.0, 16.23)], 102: [(0, 16.23), (129.97, 16.2)], 202: [(88.0, 0), (90.8, 14.84)], 131: [(129.97, 16.23), (129.97, 16.2)], 143: [(178.8, 0), (79.58, 13.8)]}, 'best_use_rate': 0.8492588235294117}, 2: {'brake_boat': {243: [(0, 0), (129.98, 16.26)], 33: [(0, 16.26), (129.92, 16.24)], 41: [(129.92, 16.26), (104.98, 16.23)], 37: [(129.98, 0), (130.0, 16.0)]}, 'best_use_rate': 0.8410925420168066}, 3: {'brake_boat': {130: [(0, 0), (129.97, 16.24)], 22: [(0, 16.24), (86.8, 16.23)], 142: [(86.8, 16.24), (85.32, 14.16)], 103: [(129.97, 0), (130.0, 16.0)], 71: [(172.12, 16.24), (90.0, 16.2)]}, 'best_use_rate': 0.8682361344537816}, 4: {'brake_boat': {182: [(0, 0), (104.88, 16.24)], 36: [(0, 16.24), (130.0, 16.0)], 45: [(104.88, 0), (56.8, 10.0)], 195: [(130.0, 16.24), (130.0, 16.0)], 54: [(161.68, 0), (99.8, 16.05)]}, 'best_use_rate': 0.8438068487394957}, 5: {'brake_boat': {221: [(0, 0), (92.0, 16.0)], 63: [(0, 16.0), (61.0, 14.0)], 201: [(61.0, 16.0), (99.8, 16.25)], 38: [(92.0, 0), (80.0, 13.63)], 177: [(160.8, 16.0), (99.8, 16.25)], 76: [(172.0, 0), (91.3, 14.8)]}, 'best_use_rate': 0.8415063025210083}, 6: {'brake_boat': {12: [(0, 0), (129.98, 16.23)], 44: [(0, 16.23), (129.98, 16.23)], 186: [(129.98, 0), (99.8, 16.25)], 13: [(129.98, 16.25), (129.9, 16.24)]}, 'best_use_rate': 0.8351341176470588}, 7: {'brake_boat': {48: [(0, 0), (105.0, 16.23)], 173: [(0, 16.23), (82.3, 14.32)], 43: [(82.3, 16.23), (86.8, 16.23)], 69: [(169.1, 16.23), (92.0, 16.24)], 58: [(105.0, 0), (130.0, 16.0)]}, 'best_use_rate': 0.8262111344537815}, 8: {'brake_boat': {250: [(0, 0), (92.0, 16.2)], 68: [(0, 16.2), (92.0, 16.24)], 237: [(92.0, 0), (82.0, 14.04)], 208: [(92.0, 14.04), (79.6, 13.62)], 184: [(171.6, 14.04), (92.0, 14.83)], 99: [(174.0, 0), (88.0, 14.0)]}, 'best_use_rate': 0.8210369747899159}, 9: {'brake_boat': {205: [(0, 0), (86.8, 16.3)], 210: [(0, 16.3), (92.0, 16.23)], 165: [(86.8, 0), (87.0, 14.8)], 224: [(92.0, 16.3), (80.0, 14.0)], 135: [(172.0, 16.3), (87.0, 14.83)], 180: [(173.8, 0), (86.0, 14.0)]}, 'best_use_rate': 0.820358193277311}, 10: {'brake_boat': {225: [(0, 0), (89.0, 15.0)], 26: [(0, 15.0), (108.0, 17.25)], 23: [(89.0, 0), (87.0, 14.83)], 3: [(108.0, 15.0), (110.0, 17.2)], 235: [(176.0, 0), (87.0, 14.0)]}, 'best_use_rate': 0.7981313025210084}, 11: {'brake_boat': {11: [(0, 0), (99.9, 16.24)], 101: [(0, 16.24), (79.8, 13.6)], 153: [(79.8, 16.24), (92.0, 16.24)], 94: [(99.9, 0), (78.0, 13.6)], 150: [(171.8, 16.24), (90.8, 14.84)], 126: [(177.9, 0), (78.0, 14.0)]}, 'best_use_rate': 0.8090344537815126}, 12: {'brake_boat': {211: [(0, 0), (99.8, 16.24)], 134: [(0, 16.24), (80.0, 14.0)], 77: [(80.0, 16.24), (92.0, 16.2)], 139: [(99.8, 0), (65.5, 10.83)], 80: [(165.3, 0), (95.0, 16.2)], 1: [(172.0, 16.24), (92.0, 16.2)]}, 'best_use_rate': 0.8371761554621847}, 13: {'brake_boat': {35: [(0, 0), (130.0, 16.0)], 251: [(0, 16.0), (99.8, 16.2)], 133: [(99.8, 16.0), (57.6, 11.9)], 30: [(130.0, 0), (100.0, 16.0)], 122: [(157.4, 16.0), (99.6, 16.2)]}, 'best_use_rate': 0.7978697478991597}, 14: {'brake_boat': {16: [(0, 0), (99.8, 16.24)], 228: [(0, 16.24), (88.0, 14.0)], 28: [(88.0, 16.24), (89.8, 16.04)], 233: [(99.8, 0), (75.7, 13.12)], 193: [(175.5, 0), (88.0, 14.0)], 189: [(177.8, 16.24), (86.0, 14.0)]}, 'best_use_rate': 0.8111689075630252}, 15: {'brake_boat': {175: [(0, 0), (104.8, 16.23)], 164: [(0, 16.23), (87.0, 14.83)], 190: [(87.0, 16.23), (78.0, 13.63)], 185: [(104.8, 0), (64.9, 11.5)], 50: [(165.0, 16.23), (95.0, 16.23)], 27: [(169.7, 0), (89.8, 14.8)]}, 'best_use_rate': 0.8058292016806723}, 16: {'brake_boat': {151: [(0, 0), (90.8, 14.84)], 156: [(0, 14.84), (79.6, 13.63)], 220: [(79.6, 14.84), (92.0, 16.0)], 174: [(90.8, 0), (87.8, 14.82)], 154: [(171.6, 14.84), (92.0, 14.8)], 152: [(178.6, 0), (82.0, 14.24)]}, 'best_use_rate': 0.8124890756302522}, 17: {'brake_boat': {105: [(0, 0), (90.0, 15.0)], 97: [(0, 15.0), (86.48, 14.24)], 82: [(86.48, 15.0), (92.0, 16.23)], 18: [(90.0, 0), (82.0, 14.03)], 19: [(172.0, 0), (92.0, 14.83)], 206: [(178.48000000000002, 15.0), (79.6, 13.6)]}, 'best_use_rate': 0.8058839495798319}, 18: {'brake_boat': {74: [(0, 0), (92.0, 14.84)], 245: [(0, 14.84), (84.0, 14.0)], 252: [(84.0, 14.84), (87.0, 15.0)], 240: [(171.0, 14.84), (90.0, 15.0)], 192: [(92.0, 0), (87.0, 14.0)], 236: [(179.0, 0), (85.0, 14.03)]}, 'best_use_rate': 0.7990367647058824}, 19: {'brake_boat': {65: [(0, 0), (99.8, 16.21)], 91: [(0, 16.21), (68.0, 11.15)], 163: [(68.0, 16.21), (87.0, 13.62)], 62: [(155.0, 16.21), (99.8, 16.25)], 234: [(99.8, 0), (74.3, 13.64)], 128: [(174.1, 0), (89.8, 14.84)]}, 'best_use_rate': 0.7908331932773109}, 20: {'brake_boat': {227: [(0, 0), (92.0, 14.84)], 166: [(0, 14.84), (109.42, 17.2)], 194: [(109.42, 14.84), (108.8, 17.25)], 160: [(92.0, 0), (80.0, 13.22)], 144: [(172.0, 0), (90.45, 14.83)]}, 'best_use_rate': 0.7902392331932775}, 21: {'brake_boat': {90: [(0, 0), (87.0, 14.83)], 241: [(0, 14.83), (105.0, 17.2)], 46: [(105.0, 14.83), (108.0, 17.25)], 92: [(87.0, 0), (92.0, 14.83)], 110: [(179.0, 0), (78.0, 13.64)]}, 'best_use_rate': 0.7759968487394958}, 22: {'brake_boat': {42: [(0, 0), (91.0, 15.0)], 81: [(0, 15.0), (105.0, 16.23)], 59: [(105.0, 15.0), (108.0, 17.0)], 196: [(91.0, 0), (86.0, 15.0)], 17: [(177.0, 0), (86.8, 14.83)]}, 'best_use_rate': 0.785965756302521}, 23: {'brake_boat': {8: [(0, 0), (89.9, 15.0)], 114: [(0, 15.0), (112.0, 17.2)], 66: [(89.9, 0), (76.7, 12.0)], 115: [(112.0, 15.0), (110.0, 16.0)], 95: [(166.60000000000002, 0), (92.0, 14.85)]}, 'best_use_rate': 0.7690651260504201}, 24: {'brake_boat': {87: [(0, 0), (79.6, 13.62)], 209: [(0, 13.62), (79.6, 13.6)], 216: [(79.6, 0), (99.0, 16.0)], 141: [(79.6, 16.0), (80.0, 13.0)], 9: [(159.6, 16.0), (102.0, 16.24)], 214: [(178.6, 0), (79.6, 13.6)]}, 'best_use_rate': 0.7909403361344536}, 25: {'brake_boat': {159: [(0, 0), (99.8, 16.3)], 183: [(0, 16.3), (80.0, 14.0)], 149: [(80.0, 16.3), (84.9, 14.03)], 217: [(99.8, 0), (79.0, 13.0)], 246: [(164.9, 16.3), (92.0, 14.8)], 161: [(178.8, 0), (79.78, 13.22)]}, 'best_use_rate': 0.7753338865546219}, 26: {'brake_boat': {4: [(0, 0), (109.7, 16.24)], 191: [(0, 16.24), (82.0, 14.0)], 207: [(82.0, 16.24), (79.6, 13.6)], 47: [(109.7, 0), (110.0, 16.0)], 6: [(161.6, 16.24), (100.0, 16.0)]}, 'best_use_rate': 0.7743789915966386}, 27: {'brake_boat': {188: [(0, 0), (86.8, 14.24)], 32: [(0, 14.24), (111.0, 18.0)], 222: [(111.0, 14.24), (110.0, 17.0)], 215: [(86.8, 0), (79.6, 13.6)], 119: [(166.39999999999998, 0), (80.0, 13.63)]}, 'best_use_rate': 0.7643899159663866}, 28: {'brake_boat': {7: [(0, 0), (86.48, 14.24)], 238: [(0, 14.24), (107.0, 17.24)], 117: [(86.48, 0), (85.28, 14.23)], 109: [(107.0, 14.24), (107.0, 17.24)], 64: [(171.76, 0), (86.86, 13.64)]}, 'best_use_rate': 0.7688172268907564}, 29: {'brake_boat': {10: [(0, 0), (104.98, 16.23)], 89: [(0, 16.23), (65.5, 10.83)], 56: [(65.5, 16.23), (100.0, 16.0)], 187: [(104.98, 0), (100.0, 16.0)], 21: [(165.5, 16.23), (93.82, 16.2)]}, 'best_use_rate': 0.7492725210084034}, 30: {'brake_boat': {137: [(0, 0), (86.48, 14.24)], 112: [(0, 14.24), (107.0, 17.24)], 200: [(107.0, 14.24), (106.0, 17.25)], 85: [(86.48, 0), (79.6, 13.6)], 181: [(166.07999999999998, 0), (86.8, 14.04)]}, 'best_use_rate': 0.7569209243697479}, 31: {'brake_boat': {107: [(0, 0), (105.0, 16.0)], 140: [(0, 16.0), (79.6, 13.63)], 253: [(79.6, 16.0), (79.6, 13.63)], 120: [(105.0, 0), (105.0, 16.0)], 78: [(159.2, 16.0), (99.8, 16.25)]}, 'best_use_rate': 0.7512233193277311}, 32: {'brake_boat': {93: [(0, 0), (98.9, 16.28)], 148: [(0, 16.28), (104.9, 16.23)], 60: [(98.9, 0), (80.0, 14.0)], 176: [(104.9, 16.28), (105.0, 16.25)], 167: [(178.9, 0), (79.0, 13.0)]}, 'best_use_rate': 0.7527173319327731}, 33: {'brake_boat': {226: [(0, 0), (105.02, 16.23)], 55: [(0, 16.23), (79.6, 13.63)], 254: [(79.6, 16.23), (83.0, 14.0)], 72: [(162.6, 16.23), (99.8, 16.25)], 106: [(105.02, 0), (99.8, 16.23)]}, 'best_use_rate': 0.7555595168067226}, 34: {'brake_boat': {242: [(0, 0), (104.81, 16.23)], 118: [(0, 16.23), (80.0, 13.63)], 162: [(80.0, 16.23), (87.0, 13.6)], 157: [(104.81, 0), (104.88, 16.23)], 61: [(167.0, 16.23), (86.8, 15.04)]}, 'best_use_rate': 0.7334391491596638}, 35: {'brake_boat': {212: [(0, 0), (105.0, 16.24)], 197: [(0, 16.24), (106.8, 16.25)], 121: [(105.0, 0), (104.81, 16.23)], 198: [(106.8, 16.24), (105.0, 16.24)]}, 'best_use_rate': 0.7192191491596639}, 36: {'brake_boat': {179: [(0, 0), (105.0, 16.25)], 248: [(0, 16.25), (104.98, 16.24)], 116: [(104.98, 16.25), (104.81, 16.23)], 213: [(105.0, 0), (105.0, 16.2)]}, 'best_use_rate': 0.7156713760504202}, 37: {'brake_boat': {40: [(0, 0), (105.0, 16.0)], 2: [(0, 16.0), (104.8, 16.24)], 100: [(104.8, 16.0), (105.0, 16.0)], 168: [(105.0, 0), (105.0, 16.0)]}, 'best_use_rate': 0.7081882352941176}, 38: {'brake_boat': {70: [(0, 0), (99.8, 16.25)], 113: [(0, 16.25), (99.6, 16.24)], 75: [(99.6, 16.25), (99.8, 16.25)], 124: [(99.8, 0), (99.8, 16.24)]}, 'best_use_rate': 0.6808567226890756}, 39: {'brake_boat': {247: [(0, 0), (99.6, 16.7)], 31: [(99.6, 0), (99.8, 16.23)], 52: [(0, 16.7), (99.8, 16.05)], 0: [(99.8, 16.7), (100.0, 16.0)]}, 'best_use_rate': 0.6811831932773109}, 40: {'brake_boat': {83: [(0, 0), (110.0, 19.25)], 158: [(110.0, 0), (107.0, 14.0)], 25: [(110.0, 14.0), (109.9, 17.24)]}, 'best_use_rate': 0.5788}, 41: {'brake_boat': {96: [(0, 0), (110.0, 19.26)], 127: [(110.0, 0), (99.6, 16.23)], 20: [(110.0, 16.23), (98.8, 16.2)]}, 'best_use_rate': 0.5604693277310924}, 42: {'brake_boat': {155: [(0, 0), (110.0, 19.28)], 169: [(110.0, 0), (110.0, 19.26)]}, 'best_use_rate': 0.44531512605042023}, 43: {'brake_boat': {132: [(0, 0), (110.0, 19.25)], 125: [(110.0, 0), (110.0, 19.25)]}, 'best_use_rate': 0.44485294117647056}, 44: {'brake_boat': {34: [(0, 0), (110.0, 19.25)], 67: [(110.0, 0), (110.0, 19.25)]}, 'best_use_rate': 0.44485294117647056}, 45: {'brake_boat': {29: [(0, 0), (110.0, 19.25)], 138: [(110.0, 0), (110.0, 19.25)]}, 'best_use_rate': 0.44485294117647056}, 46: {'brake_boat': {147: [(0, 0), (109.88, 19.25)], 170: [(109.88, 0), (110.0, 19.24)]}, 'best_use_rate': 0.44449474789915966}, 47: {'brake_boat': {172: [(0, 0), (110.0, 19.2)], 104: [(110.0, 0), (109.8, 19.25)]}, 'best_use_rate': 0.4438707983193277}, 48: {'brake_boat': {129: [(0, 0), (110.0, 19.2)], 86: [(110.0, 0), (110.0, 19.2)]}, 'best_use_rate': 0.4436974789915966}, 49: {'brake_boat': {204: [(0, 0), (110.0, 19.2)], 171: [(110.0, 0), (110.0, 19.2)]}, 'best_use_rate': 0.4436974789915966}, 50: {'brake_boat': {51: [(0, 0), (110.0, 19.2)], 249: [(110.0, 0), (110.0, 19.2)]}, 'best_use_rate': 0.4436974789915966}, 51: {'brake_boat': {98: [(0, 0), (110.0, 19.0)], 203: [(110.0, 0), (110.0, 19.2)]}, 'best_use_rate': 0.4413865546218487}, 52: {'brake_boat': {111: [(0, 0), (110.0, 17.2)], 218: [(110.0, 0), (110.0, 17.0)]}, 'best_use_rate': 0.39516806722689074}, 53: {'brake_boat': {223: [(0, 0), (110.0, 17.0)], 239: [(110.0, 0), (110.0, 17.0)]}, 'best_use_rate': 0.39285714285714285}, 54: {'brake_boat': {5: [(0, 0), (108.0, 17.25)], 108: [(108.0, 0), (108.0, 17.25)]}, 'best_use_rate': 0.39138655462184874}, 55: {'brake_boat': {88: [(0, 0), (108.0, 17.2)], 199: [(108.0, 0), (106.0, 17.28)]}, 'best_use_rate': 0.38752941176470584}, 56: {'brake_boat': {73: [(0, 0), (106.0, 17.25)], 146: [(106.0, 0), (106.0, 17.25)]}, 'best_use_rate': 0.3841386554621849}, 57: {'brake_boat': {145: [(0, 0), (106.0, 17.25)], 79: [(106.0, 0), (105.0, 17.24)]}, 'best_use_rate': 0.3822163865546218}, 58: {'brake_boat': {123: [(0, 0), (105.0, 17.2)], 84: [(105.0, 0), (105.0, 17.2)]}, 'best_use_rate': 0.37941176470588234}, 59: {'brake_boat': {15: [(0, 0), (100.02, 17.63)], 219: [(100.02, 0), (105.0, 17.0)]}, 'best_use_rate': 0.37272611344537815}, 60: {'brake_boat': {24: [(0, 0), (100.0, 17.23)], 136: [(100.0, 0), (100.2, 17.23)]}, 'best_use_rate': 0.36233676470588233}, 61: {'brake_boat': {229: [(0, 0), (100.0, 17.23)], 49: [(100.0, 0), (100.0, 17.23)]}, 'best_use_rate': 0.3619747899159664}, 62: {'brake_boat': {231: [(0, 0), (100.0, 17.23)], 232: [(100.0, 0), (100.0, 17.23)]}, 'best_use_rate': 0.3619747899159664}, 63: {'brake_boat': {230: [(0, 0), (100.0, 17.2)], 14: [(100.0, 0), (86.8, 16.2)]}, 'best_use_rate': 0.3283781512605042}}
# all_brake_boat ={0: {'brake_boat': {90: [(0, 0), (92.0, 16.24)], 27: [(0, 16.24), (129.97, 16.24)], 47: [(92.0, 0), (85.0, 14.83)], 40: [(129.97, 16.24), (130.0, 16.0)], 88: [(177.0, 0), (86.0, 14.0)]}, 'best_use_rate': 0.8560234033613445}, 1: {'brake_boat': {52: [(0, 0), (129.9, 16.25)], 57: [(0, 16.25), (92.0, 16.2)], 98: [(92.0, 16.25), (87.0, 14.83)], 166: [(129.9, 0), (130.0, 16.0)], 55: [(179.0, 16.25), (79.6, 13.6)]}, 'best_use_rate': 0.8460131302521009}, 2: {'brake_boat': {76: [(0, 0), (86.8, 16.23)], 149: [(0, 16.23), (129.97, 16.2)], 182: [(129.97, 16.23), (129.92, 16.24)], 84: [(86.8, 0), (86.8, 14.04)], 34: [(173.6, 0), (87.0, 14.82)]}, 'best_use_rate': 0.8542217226890755}, 3: {'brake_boat': {132: [(0, 0), (130.0, 16.0)], 106: [(0, 16.0), (92.0, 16.2)], 63: [(92.0, 16.0), (79.78, 13.22)], 13: [(130.0, 0), (130.0, 16.0)], 30: [(171.78, 16.0), (92.0, 14.83)]}, 'best_use_rate': 0.8476314705882352}, 4: {'brake_boat': {150: [(0, 0), (92.0, 14.85)], 108: [(0, 14.85), (112.0, 17.2)], 186: [(92.0, 0), (74.3, 13.64)], 156: [(112.0, 14.85), (129.98, 16.26)], 6: [(166.3, 0), (87.0, 14.83)]}, 'best_use_rate': 0.8098463025210084}, 5: {'brake_boat': {95: [(0, 0), (86.8, 16.3)], 17: [(0, 16.3), (90.45, 14.83)], 48: [(86.8, 0), (86.48, 14.24)], 39: [(90.45, 16.3), (87.8, 14.63)], 188: [(173.28, 0), (87.0, 14.0)], 145: [(178.25, 16.3), (85.0, 14.03)]}, 'best_use_rate': 0.8070118382352941}, 6: {'brake_boat': {26: [(0, 0), (92.0, 16.0)], 165: [(0, 16.0), (79.6, 13.62)], 49: [(79.6, 16.0), (89.8, 16.04)], 28: [(169.39999999999998, 16.0), (92.0, 16.23)], 19: [(92.0, 0), (80.0, 13.0)], 151: [(172.0, 0), (86.0, 14.0)]}, 'best_use_rate': 0.8123638655462184}, 7: {'brake_boat': {187: [(0, 0), (99.6, 16.24)], 2: [(0, 16.24), (99.0, 16.0)], 117: [(99.0, 16.24), (80.0, 13.63)], 24: [(99.6, 0), (76.7, 12.0)], 54: [(176.3, 0), (86.8, 14.24)], 16: [(179.0, 16.24), (84.9, 14.03)]}, 'best_use_rate': 0.8024667016806722}, 8: {'brake_boat': {138: [(0, 0), (99.8, 16.3)], 116: [(0, 16.3), (80.0, 14.0)], 82: [(80.0, 16.3), (87.0, 14.83)], 161: [(99.8, 0), (65.5, 10.83)], 136: [(165.3, 0), (92.0, 14.83)], 102: [(167.0, 16.3), (92.0, 16.2)]}, 'best_use_rate': 0.7984322478991596}, 9: {'brake_boat': {91: [(0, 0), (102.0, 16.24)], 162: [(0, 16.24), (87.0, 14.83)], 78: [(87.0, 16.24), (89.8, 14.8)], 56: [(102.0, 0), (64.9, 11.5)], 46: [(166.9, 0), (94.8, 16.23)], 129: [(176.8, 16.24), (87.0, 13.6)]}, 'best_use_rate': 0.8134331932773109}, 10: {'brake_boat': {169: [(0, 0), (90.0, 15.0)], 101: [(0, 15.0), (107.0, 17.24)], 20: [(90.0, 0), (87.0, 15.0)], 60: [(107.0, 15.0), (129.98, 16.26)], 171: [(177.0, 0), (82.0, 14.0)]}, 'best_use_rate': 0.8152473529411765}, 11: {'brake_boat': {128: [(0, 0), (95.0, 16.23)], 68: [(0, 16.23), (90.8, 14.84)], 181: [(90.8, 16.23), (79.58, 13.8)], 77: [(95.0, 0), (79.6, 13.6)], 14: [(170.38, 16.23), (87.3, 13.23)], 163: [(174.6, 0), (87.0, 13.62)]}, 'best_use_rate': 0.7783618697478991}, 12: {'brake_boat': {93: [(0, 0), (89.8, 14.84)], 41: [(0, 14.84), (99.8, 16.24)], 83: [(89.8, 0), (85.28, 14.23)], 18: [(99.8, 14.84), (79.0, 13.0)], 87: [(175.07999999999998, 0), (87.8, 14.82)], 118: [(178.8, 14.84), (80.0, 13.63)]}, 'best_use_rate': 0.796797731092437}, 13: {'brake_boat': {12: [(0, 0), (109.7, 16.24)], 36: [(0, 16.24), (78.0, 14.0)], 92: [(78.0, 16.24), (86.0, 15.0)], 175: [(109.7, 0), (105.0, 16.0)], 67: [(164.0, 16.24), (100.0, 16.0)]}, 'best_use_rate': 0.7818831932773109}, 14: {'brake_boat': {179: [(0, 0), (86.8, 14.83)], 115: [(0, 14.83), (80.0, 14.0)], 164: [(80.0, 14.83), (78.0, 13.63)], 53: [(86.8, 0), (80.0, 14.0)], 29: [(158.0, 14.83), (105.0, 17.2)], 31: [(166.8, 0), (92.0, 14.8)]}, 'best_use_rate': 0.8149142857142857}, 15: {'brake_boat': {86: [(0, 0), (92.0, 14.84)], 61: [(0, 14.84), (108.0, 17.25)], 15: [(92.0, 0), (83.0, 13.84)], 123: [(108.0, 14.84), (110.0, 17.0)], 112: [(175.0, 0), (86.86, 13.64)]}, 'best_use_rate': 0.7806481512605042}, 16: {'brake_boat': {158: [(0, 0), (99.8, 16.25)], 22: [(0, 16.25), (80.0, 13.22)], 148: [(80.0, 16.25), (79.8, 13.6)], 141: [(99.8, 0), (79.0, 13.0)], 73: [(159.8, 16.25), (99.8, 16.05)], 32: [(178.8, 0), (79.6, 13.62)]}, 'best_use_rate': 0.785459243697479}, 17: {'brake_boat': {120: [(0, 0), (92.0, 14.83)], 21: [(0, 14.83), (105.02, 16.23)], 143: [(92.0, 0), (82.0, 14.04)], 44: [(105.02, 14.83), (108.0, 17.25)], 185: [(174.0, 0), (86.0, 14.0)]}, 'best_use_rate': 0.7654532142857142}, 18: {'brake_boat': {167: [(0, 0), (90.8, 14.84)], 180: [(0, 14.84), (105.0, 16.24)], 85: [(90.8, 0), (80.0, 13.08)], 64: [(105.0, 14.84), (65.5, 10.83)], 142: [(170.5, 14.84), (86.8, 16.23)], 99: [(170.8, 0), (79.6, 13.6)]}, 'best_use_rate': 0.7667816176470589}, 19: {'brake_boat': {81: [(0, 0), (105.0, 16.23)], 131: [(0, 16.23), (75.7, 13.12)], 146: [(75.7, 16.23), (87.0, 14.8)], 59: [(105.0, 0), (105.0, 16.23)], 111: [(162.7, 16.23), (99.8, 16.2)]}, 'best_use_rate': 0.7674205882352942}, 20: {'brake_boat': {139: [(0, 0), (86.48, 14.24)], 133: [(0, 14.24), (110.0, 17.2)], 119: [(110.0, 14.24), (110.0, 17.0)], 8: [(86.48, 0), (79.6, 13.6)], 155: [(166.07999999999998, 0), (88.0, 14.0)]}, 'best_use_rate': 0.767650756302521}, 21: {'brake_boat': {144: [(0, 0), (99.8, 16.25)], 114: [(0, 16.25), (93.82, 16.2)], 153: [(93.82, 16.25), (79.6, 13.6)], 42: [(99.8, 0), (105.0, 16.0)], 157: [(173.42, 16.25), (87.0, 14.0)]}, 'best_use_rate': 0.7481296218487394}, 22: {'brake_boat': {110: [(0, 0), (92.0, 16.24)], 168: [(0, 16.24), (99.8, 16.24)], 100: [(92.0, 0), (84.0, 14.0)], 160: [(99.8, 16.24), (105.0, 16.0)], 35: [(176.0, 0), (87.0, 13.62)]}, 'best_use_rate': 0.7516567226890756}, 23: {'brake_boat': {97: [(0, 0), (98.8, 16.2)], 96: [(0, 16.2), (100.0, 16.0)], 127: [(100.0, 16.2), (106.8, 16.25)], 147: [(98.8, 0), (79.6, 13.63)], 23: [(178.39999999999998, 0), (78.0, 13.64)]}, 'best_use_rate': 0.7442151260504202}, 24: {'brake_boat': {43: [(0, 0), (105.0, 16.25)], 104: [(0, 16.25), (104.81, 16.23)], 173: [(104.81, 16.25), (110.0, 16.0)], 33: [(105.0, 0), (105.0, 16.2)]}, 'best_use_rate': 0.7214617962184874}, 25: {'brake_boat': {65: [(0, 0), (105.02, 16.23)], 58: [(0, 16.23), (104.98, 16.23)], 105: [(104.98, 16.23), (99.8, 16.25)], 7: [(105.02, 0), (105.0, 16.0)]}, 'best_use_rate': 0.7048371848739496}, 26: {'brake_boat': {37: [(0, 0), (107.0, 14.0)], 183: [(0, 14.0), (107.0, 17.24)], 176: [(107.0, 0), (104.81, 16.23)], 154: [(107.0, 16.23), (99.8, 16.21)]}, 'best_use_rate': 0.6997378466386555}, 27: {'brake_boat': {170: [(0, 0), (105.0, 16.0)], 109: [(0, 16.0), (99.6, 16.7)], 189: [(99.6, 16.0), (99.6, 16.23)], 107: [(105.0, 0), (100.0, 16.0)]}, 'best_use_rate': 0.68905756302521}, 28: {'brake_boat': {75: [(0, 0), (99.8, 16.25)], 137: [(0, 16.25), (99.9, 16.24)], 184: [(99.8, 0), (99.8, 16.25)], 3: [(99.9, 16.25), (99.8, 16.25)]}, 'best_use_rate': 0.6814733193277311}, 29: {'brake_boat': {159: [(0, 0), (100.0, 16.0)], 121: [(0, 16.0), (99.8, 16.25)], 74: [(99.8, 16.0), (99.8, 16.25)], 89: [(100.0, 0), (100.0, 16.0)]}, 'best_use_rate': 0.6768382352941177}, 30: {'brake_boat': {50: [(0, 0), (86.48, 14.24)], 51: [(0, 14.24), (110.0, 17.2)], 4: [(110.0, 14.24), (106.0, 17.28)], 140: [(86.48, 0), (85.32, 14.16)]}, 'best_use_rate': 0.6474040336134453}, 31: {'brake_boat': {11: [(0, 0), (110.0, 19.28)], 69: [(110.0, 0), (110.0, 19.26)]}, 'best_use_rate': 0.44531512605042023}, 32: {'brake_boat': {80: [(0, 0), (110.0, 19.25)], 5: [(110.0, 0), (110.0, 19.25)]}, 'best_use_rate': 0.44485294117647056}, 33: {'brake_boat': {0: [(0, 0), (110.0, 19.25)], 70: [(110.0, 0), (110.0, 19.25)]}, 'best_use_rate': 0.44485294117647056}, 34: {'brake_boat': {1: [(0, 0), (110.0, 19.24)], 125: [(110.0, 0), (110.0, 19.25)]}, 'best_use_rate': 0.44473739495798315}, 35: {'brake_boat': {177: [(0, 0), (110.0, 19.2)], 25: [(110.0, 0), (109.8, 19.25)]}, 'best_use_rate': 0.4438707983193277}, 36: {'brake_boat': {72: [(0, 0), (110.0, 19.2)], 62: [(110.0, 0), (110.0, 19.2)]}, 'best_use_rate': 0.4436974789915966}, 37: {'brake_boat': {79: [(0, 0), (110.0, 19.2)], 135: [(110.0, 0), (110.0, 19.2)]}, 'best_use_rate': 0.4436974789915966}, 38: {'brake_boat': {10: [(0, 0), (110.0, 19.2)], 71: [(110.0, 0), (110.0, 19.2)]}, 'best_use_rate': 0.4436974789915966}, 39: {'brake_boat': {130: [(0, 0), (110.0, 17.0)], 124: [(110.0, 0), (110.0, 18.0)]}, 'best_use_rate': 0.40441176470588236}, 40: {'brake_boat': {122: [(0, 0), (108.0, 17.25)], 94: [(108.0, 0), (108.0, 17.25)]}, 'best_use_rate': 0.39138655462184874}, 41: {'brake_boat': {174: [(0, 0), (107.0, 17.24)], 152: [(107.0, 0), (108.0, 17.2)]}, 'best_use_rate': 0.38889495798319323}, 42: {'brake_boat': {126: [(0, 0), (106.0, 17.25)], 38: [(106.0, 0), (108.0, 17.0)]}, 'best_use_rate': 0.3849264705882353}, 43: {'brake_boat': {172: [(0, 0), (105.0, 17.24)], 103: [(105.0, 0), (106.0, 17.25)]}, 'best_use_rate': 0.3822163865546218}, 44: {'brake_boat': {134: [(0, 0), (105.0, 17.2)], 9: [(105.0, 0), (105.0, 17.0)]}, 'best_use_rate': 0.37720588235294117}, 45: {'brake_boat': {66: [(0, 0), (100.2, 17.23)], 113: [(100.2, 0), (100.0, 17.23)]}, 'best_use_rate': 0.36233676470588233}, 46: {'brake_boat': {45: [(0, 0), (99.8, 16.23)], 178: [(99.8, 0), (100.0, 17.2)]}, 'best_use_rate': 0.3508144957983193}}

# all_brake_boat= {0: {'brake_boat': {27: [(0, 0), (129.97, 16.24)], 33: [(0, 16.24), (105.0, 16.2)], 52: [(105.0, 16.24), (129.9, 16.25)], 40: [(129.97, 0), (130.0, 16.0)]}, 'best_use_rate': 0.8406079621848739}, 1: {'brake_boat': {17: [(0, 0), (90.45, 14.83)], 13: [(0, 14.83), (130.0, 16.0)], 9: [(130.0, 14.83), (105.0, 17.0)], 34: [(90.45, 0), (87.0, 14.82)], 47: [(177.45, 0), (85.0, 14.83)]}, 'best_use_rate': 0.8147335609243698}, 2: {'brake_boat': {28: [(0, 0), (92.0, 16.23)], 36: [(0, 16.23), (78.0, 14.0)], 2: [(78.0, 16.23), (99.0, 16.0)], 53: [(92.0, 0), (80.0, 14.0)], 49: [(172.0, 0), (89.8, 16.04)], 8: [(177.0, 16.23), (79.6, 13.6)]}, 'best_use_rate': 0.8205999999999999}, 3: {'brake_boat': {26: [(0, 0), (92.0, 16.0)], 15: [(0, 16.0), (83.0, 13.84)], 31: [(83.0, 16.0), (92.0, 14.8)], 16: [(92.0, 0), (84.9, 14.03)], 50: [(175.0, 16.0), (86.48, 14.24)], 48: [(176.9, 0), (86.48, 14.24)]}, 'best_use_rate': 0.8021446848739496}, 4: {'brake_boat': {45: [(0, 0), (99.8, 16.23)], 24: [(0, 16.23), (76.7, 12.0)], 46: [(76.7, 16.23), (94.8, 16.23)], 23: [(99.8, 0), (78.0, 13.64)], 20: [(171.5, 16.23), (87.0, 15.0)], 32: [(177.8, 0), (79.6, 13.62)]}, 'best_use_rate': 0.7911586134453782}, 5: {'brake_boat': {39: [(0, 0), (87.8, 14.63)], 51: [(0, 14.63), (110.0, 17.2)], 54: [(87.8, 0), (86.8, 14.24)], 56: [(110.0, 14.63), (64.9, 11.5)], 35: [(174.6, 0), (87.0, 13.62)], 6: [(174.9, 14.63), (87.0, 14.83)]}, 'best_use_rate': 0.8018955882352942}, 6: {'brake_boat': {14: [(0, 0), (87.3, 13.23)], 1: [(0, 13.23), (110.0, 19.24)], 19: [(87.3, 0), (80.0, 13.0)], 5: [(110.0, 13.23), (110.0, 19.25)], 22: [(167.3, 0), (80.0, 13.22)]}, 'best_use_rate': 0.7863948529411765}, 7: {'brake_boat': {12: [(0, 0), (109.7, 16.24)], 18: [(0, 16.24), (79.0, 13.0)], 3: [(79.0, 16.24), (99.8, 16.25)], 21: [(109.7, 0), (105.02, 16.23)], 55: [(178.8, 16.24), (79.6, 13.6)]}, 'best_use_rate': 0.7581210714285713}, 8: {'brake_boat': {42: [(0, 0), (105.0, 16.0)], 43: [(0, 16.0), (105.0, 16.25)], 37: [(105.0, 0), (107.0, 14.0)], 44: [(105.0, 14.0), (108.0, 17.25)]}, 'best_use_rate': 0.7087447478991596}, 9: {'brake_boat': {11: [(0, 0), (110.0, 19.28)], 41: [(110.0, 0), (99.8, 16.24)], 7: [(110.0, 16.24), (105.0, 16.0)]}, 'best_use_rate': 0.569490756302521}, 10: {'brake_boat': {0: [(0, 0), (110.0, 19.25)], 30: [(110.0, 0), (92.0, 14.83)], 38: [(110.0, 14.83), (108.0, 17.0)]}, 'best_use_rate': 0.5585987394957983}, 11: {'brake_boat': {10: [(0, 0), (110.0, 19.2)], 25: [(110.0, 0), (109.8, 19.25)]}, 'best_use_rate': 0.4438707983193277}, 12: {'brake_boat': {4: [(0, 0), (106.0, 17.28)], 29: [(106.0, 0), (105.0, 17.2)]}, 'best_use_rate': 0.382109243697479}}
# all_brake_boat ={0: {'brake_boat': {38: [(0, 0), (86.8, 16.3)], 2: [(0, 16.3), (105.0, 16.23)], 58: [(86.8, 0), (80.0, 14.0)], 3: [(105.0, 16.3), (129.98, 16.26)], 45: [(166.8, 0), (92.0, 16.2)]}, 'best_use_rate': 0.8238303361344537}, 1: {'brake_boat': {33: [(0, 0), (92.0, 16.24)], 19: [(0, 16.24), (86.8, 16.23)], 59: [(86.8, 16.24), (80.0, 14.0)], 60: [(92.0, 0), (80.0, 13.63)], 29: [(166.8, 16.24), (92.0, 14.84)], 49: [(172.0, 0), (92.0, 16.2)]}, 'best_use_rate': 0.8370718487394958}, 2: {'brake_boat': {41: [(0, 0), (87.0, 14.83)], 25: [(0, 14.83), (87.0, 14.83)], 30: [(87.0, 0), (87.8, 14.82)], 35: [(87.0, 14.82), (86.0, 15.0)], 36: [(173.0, 14.82), (89.8, 14.84)], 26: [(174.8, 0), (85.28, 14.23)]}, 'best_use_rate': 0.8106914285714286}, 3: {'brake_boat': {53: [(0, 0), (92.0, 16.24)], 43: [(0, 16.24), (84.0, 14.0)], 28: [(84.0, 16.24), (80.0, 13.08)], 20: [(92.0, 0), (79.6, 13.6)], 54: [(164.0, 16.24), (99.8, 16.2)], 21: [(171.6, 0), (89.8, 14.8)]}, 'best_use_rate': 0.8135336134453781}, 4: {'brake_boat': {11: [(0, 0), (90.8, 14.84)], 44: [(0, 14.84), (107.0, 17.24)], 52: [(107.0, 14.84), (99.6, 16.7)], 55: [(90.8, 0), (86.86, 13.64)], 31: [(177.66, 0), (86.0, 14.0)]}, 'best_use_rate': 0.7609498319327731}, 5: {'brake_boat': {47: [(0, 0), (104.81, 16.23)], 0: [(0, 16.23), (92.0, 16.2)], 7: [(92.0, 16.23), (65.5, 10.83)], 24: [(104.81, 0), (105.0, 16.23)], 40: [(157.5, 16.23), (98.8, 16.2)]}, 'best_use_rate': 0.7568845903361343}, 6: {'brake_boat': {27: [(0, 0), (86.8, 14.04)], 37: [(0, 14.04), (108.0, 17.25)], 6: [(86.8, 0), (79.78, 13.22)], 51: [(108.0, 14.04), (112.0, 17.2)], 61: [(166.57999999999998, 0), (80.0, 13.63)]}, 'best_use_rate': 0.7513827310924369}, 7: {'brake_boat': {34: [(0, 0), (102.0, 16.24)], 8: [(0, 16.24), (105.02, 16.23)], 1: [(102.0, 0), (104.98, 16.23)], 17: [(105.02, 16.24), (99.8, 16.25)]}, 'best_use_rate': 0.7023665966386555}, 8: {'brake_boat': {48: [(0, 0), (99.8, 16.25)], 10: [(0, 16.25), (100.0, 16.0)], 18: [(99.8, 0), (99.8, 16.25)], 16: [(100.0, 16.25), (99.8, 16.05)]}, 'best_use_rate': 0.6770262605042017}, 9: {'brake_boat': {32: [(0, 0), (100.0, 16.0)], 39: [(0, 16.0), (100.0, 16.0)], 42: [(100.0, 0), (79.6, 13.6)], 14: [(100.0, 13.6), (110.0, 19.2)]}, 'best_use_rate': 0.6716974789915966}, 10: {'brake_boat': {12: [(0, 0), (110.0, 19.26)], 50: [(110.0, 0), (100.0, 16.0)], 57: [(110.0, 16.0), (93.82, 16.2)]}, 'best_use_rate': 0.5502609243697479}, 11: {'brake_boat': {23: [(0, 0), (110.0, 19.25)], 13: [(110.0, 0), (110.0, 19.25)]}, 'best_use_rate': 0.44485294117647056}, 12: {'brake_boat': {5: [(0, 0), (110.0, 19.2)], 15: [(110.0, 0), (110.0, 19.2)]}, 'best_use_rate': 0.4436974789915966}, 13: {'brake_boat': {22: [(0, 0), (110.0, 19.2)], 4: [(110.0, 0), (108.0, 17.25)]}, 'best_use_rate': 0.4175420168067227}, 14: {'brake_boat': {46: [(0, 0), (106.0, 17.25)], 9: [(106.0, 0), (100.2, 17.23)]}, 'best_use_rate': 0.3734186974789916}, 15: {'brake_boat': {56: [(0, 0), (100.0, 17.23)]}, 'best_use_rate': 0.1809873949579832}}
all_brake_boat ={0: {'brake_boat': {70: [(0, 0), (99.6, 16.23)], 63: [(0, 16.23), (129.92, 16.24)], 45: [(99.6, 0), (78.0, 13.63)], 13: [(129.92, 16.23), (130.0, 16.0)], 66: [(177.6, 0), (86.0, 14.0)]}, 'best_use_rate': 0.8480618487394957}, 1: {'brake_boat': {60: [(0, 0), (86.8, 14.83)], 37: [(0, 14.83), (129.98, 16.26)], 30: [(129.98, 14.83), (129.97, 16.2)], 52: [(86.8, 0), (82.0, 14.0)], 43: [(168.8, 0), (87.0, 14.83)]}, 'best_use_rate': 0.834500294117647}, 2: {'brake_boat': {17: [(0, 0), (92.0, 14.83)], 47: [(0, 14.83), (130.0, 16.0)], 14: [(130.0, 14.83), (110.0, 17.2)], 69: [(92.0, 0), (87.0, 14.0)], 26: [(179.0, 0), (85.0, 14.03)]}, 'best_use_rate': 0.813751050420168}, 3: {'brake_boat': {1: [(0, 0), (92.0, 14.83)], 46: [(0, 14.83), (79.6, 13.62)], 12: [(79.6, 14.83), (75.7, 13.12)], 15: [(155.3, 14.83), (105.0, 17.2)], 20: [(92.0, 0), (86.48, 14.24)], 24: [(178.48000000000002, 0), (82.0, 14.04)]}, 'best_use_rate': 0.8015179831932773}, 4: {'brake_boat': {65: [(0, 0), (99.8, 16.25)], 29: [(0, 16.25), (79.8, 13.6)], 44: [(79.8, 16.25), (87.0, 13.62)], 67: [(99.8, 0), (74.3, 13.64)], 23: [(166.8, 16.25), (86.8, 16.23)], 27: [(174.1, 0), (87.0, 14.8)]}, 'best_use_rate': 0.7985069327731092}, 5: {'brake_boat': {50: [(0, 0), (90.0, 15.0)], 4: [(0, 15.0), (110.0, 17.0)], 34: [(90.0, 0), (79.6, 13.6)], 55: [(110.0, 15.0), (107.0, 17.24)], 31: [(169.6, 0), (92.0, 14.85)]}, 'best_use_rate': 0.7892268907563025}, 6: {'brake_boat': {48: [(0, 0), (90.8, 14.84)], 33: [(0, 14.84), (108.0, 17.2)], 3: [(108.0, 14.84), (108.0, 17.25)], 62: [(90.8, 0), (79.58, 13.8)], 32: [(170.38, 0), (86.0, 14.0)]}, 'best_use_rate': 0.7741886554621848}, 7: {'brake_boat': {21: [(0, 0), (85.32, 14.16)], 5: [(0, 14.16), (110.0, 18.0)], 38: [(85.32, 0), (87.0, 14.0)], 0: [(110.0, 14.16), (110.0, 17.0)], 10: [(172.32, 0), (87.0, 13.6)]}, 'best_use_rate': 0.7835431932773109}, 8: {'brake_boat': {57: [(0, 0), (104.81, 16.23)], 42: [(0, 16.23), (65.5, 10.83)], 2: [(65.5, 16.23), (99.8, 16.25)], 41: [(104.81, 0), (105.0, 16.0)], 9: [(165.3, 16.23), (95.0, 16.23)]}, 'best_use_rate': 0.7619780777310925}, 9: {'brake_boat': {54: [(0, 0), (110.0, 16.0)], 28: [(0, 16.0), (79.6, 13.63)], 22: [(79.6, 16.0), (79.0, 13.0)], 61: [(158.6, 16.0), (105.0, 16.24)], 56: [(110.0, 0), (105.0, 16.0)]}, 'best_use_rate': 0.7623054621848739}, 10: {'brake_boat': {19: [(0, 0), (99.8, 16.3)], 51: [(0, 16.3), (105.0, 16.0)], 8: [(99.8, 0), (106.8, 16.25)], 18: [(105.0, 16.3), (99.9, 16.24)]}, 'best_use_rate': 0.7000647058823529}, 11: {'brake_boat': {35: [(0, 0), (99.8, 16.21)], 49: [(0, 16.21), (99.8, 16.24)], 25: [(99.8, 0), (99.8, 16.25)], 39: [(99.8, 16.25), (99.8, 16.25)]}, 'best_use_rate': 0.6808834033613446}, 12: {'brake_boat': {40: [(0, 0), (100.0, 16.0)], 6: [(100.0, 0), (110.0, 19.25)], 68: [(0, 16.0), (99.6, 16.24)]}, 'best_use_rate': 0.5603995798319328}, 13: {'brake_boat': {58: [(0, 0), (110.0, 19.2)], 36: [(110.0, 0), (88.0, 14.0)], 11: [(110.0, 14.0), (110.0, 17.0)]}, 'best_use_rate': 0.5476890756302522}, 14: {'brake_boat': {64: [(0, 0), (107.0, 17.24)], 16: [(107.0, 0), (110.0, 19.2)]}, 'best_use_rate': 0.41561764705882354}, 15: {'brake_boat': {53: [(0, 0), (105.0, 17.24)], 7: [(105.0, 0), (106.0, 17.25)]}, 'best_use_rate': 0.3822163865546218}, 16: {'brake_boat': {59: [(0, 0), (100.0, 17.2)]}, 'best_use_rate': 0.18067226890756302}}

In [364]:
all_brake_boat

{0: {'brake_boat': {70: [(0, 0), (99.6, 16.23)],
   63: [(0, 16.23), (129.92, 16.24)],
   45: [(99.6, 0), (78.0, 13.63)],
   13: [(129.92, 16.23), (130.0, 16.0)],
   66: [(177.6, 0), (86.0, 14.0)]},
  'best_use_rate': 0.8480618487394957},
 1: {'brake_boat': {60: [(0, 0), (86.8, 14.83)],
   37: [(0, 14.83), (129.98, 16.26)],
   30: [(129.98, 14.83), (129.97, 16.2)],
   52: [(86.8, 0), (82.0, 14.0)],
   43: [(168.8, 0), (87.0, 14.83)]},
  'best_use_rate': 0.834500294117647},
 2: {'brake_boat': {17: [(0, 0), (92.0, 14.83)],
   47: [(0, 14.83), (130.0, 16.0)],
   14: [(130.0, 14.83), (110.0, 17.2)],
   69: [(92.0, 0), (87.0, 14.0)],
   26: [(179.0, 0), (85.0, 14.03)]},
  'best_use_rate': 0.813751050420168},
 3: {'brake_boat': {1: [(0, 0), (92.0, 14.83)],
   46: [(0, 14.83), (79.6, 13.62)],
   12: [(79.6, 14.83), (75.7, 13.12)],
   15: [(155.3, 14.83), (105.0, 17.2)],
   20: [(92.0, 0), (86.48, 14.24)],
   24: [(178.48000000000002, 0), (82.0, 14.04)]},
  'best_use_rate': 0.8015179831932773},
 4: {'brake_boat': {65: [(0, 0), (99.8, 16.25)],
   29: [(0, 16.25), (79.8, 13.6)],
   44: [(79.8, 16.25), (87.0, 13.62)],
   67: [(99.8, 0), (74.3, 13.64)],
   23: [(166.8, 16.25), (86.8, 16.23)],
   27: [(174.1, 0), (87.0, 14.8)]},
  'best_use_rate': 0.7985069327731092},
 5: {'brake_boat': {50: [(0, 0), (90.0, 15.0)],
   4: [(0, 15.0), (110.0, 17.0)],
   34: [(90.0, 0), (79.6, 13.6)],
   55: [(110.0, 15.0), (107.0, 17.24)],
   31: [(169.6, 0), (92.0, 14.85)]},
  'best_use_rate': 0.7892268907563025},
 6: {'brake_boat': {48: [(0, 0), (90.8, 14.84)],
   33: [(0, 14.84), (108.0, 17.2)],
   3: [(108.0, 14.84), (108.0, 17.25)],
   62: [(90.8, 0), (79.58, 13.8)],
   32: [(170.38, 0), (86.0, 14.0)]},
  'best_use_rate': 0.7741886554621848},
 7: {'brake_boat': {21: [(0, 0), (85.32, 14.16)],
   5: [(0, 14.16), (110.0, 18.0)],
   38: [(85.32, 0), (87.0, 14.0)],
   0: [(110.0, 14.16), (110.0, 17.0)],
   10: [(172.32, 0), (87.0, 13.6)]},
  'best_use_rate': 0.7835431932773109},
 8: {'brake_boat': {57: [(0, 0), (104.81, 16.23)],
   42: [(0, 16.23), (65.5, 10.83)],
   2: [(65.5, 16.23), (99.8, 16.25)],
   41: [(104.81, 0), (105.0, 16.0)],
   9: [(165.3, 16.23), (95.0, 16.23)]},
  'best_use_rate': 0.7619780777310925},
 9: {'brake_boat': {54: [(0, 0), (110.0, 16.0)],
   28: [(0, 16.0), (79.6, 13.63)],
   22: [(79.6, 16.0), (79.0, 13.0)],
   61: [(158.6, 16.0), (105.0, 16.24)],
   56: [(110.0, 0), (105.0, 16.0)]},
  'best_use_rate': 0.7623054621848739},
 10: {'brake_boat': {19: [(0, 0), (99.8, 16.3)],
   51: [(0, 16.3), (105.0, 16.0)],
   8: [(99.8, 0), (106.8, 16.25)],
   18: [(105.0, 16.3), (99.9, 16.24)]},
  'best_use_rate': 0.7000647058823529},
 11: {'brake_boat': {35: [(0, 0), (99.8, 16.21)],
   49: [(0, 16.21), (99.8, 16.24)],
   25: [(99.8, 0), (99.8, 16.25)],
   39: [(99.8, 16.25), (99.8, 16.25)]},
  'best_use_rate': 0.6808834033613446},
 12: {'brake_boat': {40: [(0, 0), (100.0, 16.0)],
   6: [(100.0, 0), (110.0, 19.25)],
   68: [(0, 16.0), (99.6, 16.24)]},
  'best_use_rate': 0.5603995798319328},
 13: {'brake_boat': {58: [(0, 0), (110.0, 19.2)],
   36: [(110.0, 0), (88.0, 14.0)],
   11: [(110.0, 14.0), (110.0, 17.0)]},
  'best_use_rate': 0.5476890756302522},
 14: {'brake_boat': {64: [(0, 0), (107.0, 17.24)],
   16: [(107.0, 0), (110.0, 19.2)]},
  'best_use_rate': 0.41561764705882354},
 15: {'brake_boat': {53: [(0, 0), (105.0, 17.24)],
   7: [(105.0, 0), (106.0, 17.25)]},
  'best_use_rate': 0.3822163865546218},
 16: {'brake_boat': {59: [(0, 0), (100.0, 17.2)]},
  'best_use_rate': 0.18067226890756302}}

In [365]:
all_brake_boat_new={}
for k ,v in all_brake_boat.items():
    brake_boat=v['brake_boat']
#     print(k,v,'\n')
    brake_boat_new={ind_name[k0]:v0 for k0,v0 in brake_boat.items()}
    all_brake_boat_new[k]={'brake_boat':brake_boat_new,'best_use_rate':v['best_use_rate']}

In [366]:
all_brake_boat_new

{0: {'brake_boat': {'千千988': [(0, 0), (99.6, 16.23)],
   '海牛1009': [(0, 16.23), (129.92, 16.24)],
   '宜都广翼196': [(99.6, 0), (78.0, 13.63)],
   '海牛69': [(129.92, 16.23), (130.0, 16.0)],
   '宏青818': [(177.6, 0), (86.0, 14.0)]},
  'best_use_rate': 0.8480618487394957},
 1: {'brake_boat': {'鄂石2176': [(0, 0), (86.8, 14.83)],
   '长兴1868': [(0, 14.83), (129.98, 16.26)],
   '龙昊1005': [(129.98, 14.83), (129.97, 16.2)],
   '宜化6号': [(86.8, 0), (82.0, 14.0)],
   '新平江3003': [(168.8, 0), (87.0, 14.83)]},
  'best_use_rate': 0.834500294117647},
 2: {'brake_boat': {'砚海998': [(0, 0), (92.0, 14.83)],
   '恒洋18': [(0, 14.83), (130.0, 16.0)],
   '镔港808': [(130.0, 14.83), (110.0, 17.2)],
   '永通6': [(92.0, 0), (87.0, 14.0)],
   '云隆88': [(179.0, 0), (85.0, 14.03)]},
  'best_use_rate': 0.813751050420168},
 3: {'brake_boat': {'飞艳18': [(0, 0), (92.0, 14.83)],
   '江韵1008': [(0, 14.83), (79.6, 13.62)],
   '云浩818': [(79.6, 14.83), (75.7, 13.12)],
   '平洋898': [(155.3, 14.83), (105.0, 17.2)],
   '川北988': [(92.0, 0), (86.48, 14.24)],
   '长安69': [(178.48000000000002, 0), (82.0, 14.04)]},
  'best_use_rate': 0.8015179831932773},
 4: {'brake_boat': {'江泓898': [(0, 0), (99.8, 16.25)],
   '领航飞翔': [(0, 16.25), (79.8, 13.6)],
   '新平江1028': [(79.8, 16.25), (87.0, 13.62)],
   '云浩918': [(99.8, 0), (74.3, 13.64)],
   '航兴901': [(166.8, 16.25), (86.8, 16.23)],
   '新平江3005': [(174.1, 0), (87.0, 14.8)]},
  'best_use_rate': 0.7985069327731092},
 5: {'brake_boat': {'龙腾819': [(0, 0), (90.0, 15.0)],
   '长荣998': [(0, 15.0), (110.0, 17.0)],
   '豫宛货2077': [(90.0, 0), (79.6, 13.6)],
   '长航集运0335': [(110.0, 15.0), (107.0, 17.24)],
   '九五888': [(169.6, 0), (92.0, 14.85)]},
  'best_use_rate': 0.7892268907563025},
 6: {'brake_boat': {'天畅908': [(0, 0), (90.8, 14.84)],
   '金海168': [(0, 14.84), (108.0, 17.2)],
   '港盛1618': [(108.0, 14.84), (108.0, 17.25)],
   '曙光888': [(90.8, 0), (79.58, 13.8)],
   '天龙贰号': [(170.38, 0), (86.0, 14.0)]},
  'best_use_rate': 0.7741886554621848},
 7: {'brake_boat': {'曙光668': [(0, 0), (85.32, 14.16)],
   '海辉307': [(0, 14.16), (110.0, 18.0)],
   '云浩999': [(85.32, 0), (87.0, 14.0)],
   '豫信货17788': [(110.0, 14.16), (110.0, 17.0)],
   '新平江1009': [(172.32, 0), (87.0, 13.6)]},
  'best_use_rate': 0.7835431932773109},
 8: {'brake_boat': {'长兴1015': [(0, 0), (104.81, 16.23)],
   '金河18': [(0, 16.23), (65.5, 10.83)],
   '吉耘918': [(65.5, 16.23), (99.8, 16.25)],
   '航平906': [(104.81, 0), (105.0, 16.0)],
   '和海66': [(165.3, 16.23), (95.0, 16.23)]},
  'best_use_rate': 0.7619780777310925},
 9: {'brake_boat': {'浩航1009': [(0, 0), (110.0, 16.0)],
   '盛畅8198': [(0, 16.0), (79.6, 13.63)],
   '新宜超越': [(79.6, 16.0), (79.0, 13.0)],
   '豫信货13986': [(158.6, 16.0), (105.0, 16.24)],
   '林瑞9': [(110.0, 0), (105.0, 16.0)]},
  'best_use_rate': 0.7623054621848739},
 10: {'brake_boat': {'祥牛6': [(0, 0), (99.8, 16.3)],
   '鹏杰8': [(0, 16.3), (105.0, 16.0)],
   '渝山988': [(99.8, 0), (106.8, 16.25)],
   '帝豪8': [(105.0, 16.3), (99.9, 16.24)]},
  'best_use_rate': 0.7000647058823529},
 11: {'brake_boat': {'宏源819': [(0, 0), (99.8, 16.21)],
   '浦航998': [(0, 16.21), (99.8, 16.24)],
   '兴晟05': [(99.8, 0), (99.8, 16.25)],
   '宏河918': [(99.8, 16.25), (99.8, 16.25)]},
  'best_use_rate': 0.6808834033613446},
 12: {'brake_boat': {'宜昌金航66': [(0, 0), (100.0, 16.0)],
   '国祥898': [(100.0, 0), (110.0, 19.25)],
   '民联908': [(0, 16.0), (99.6, 16.24)]},
  'best_use_rate': 0.5603995798319328},
 13: {'brake_boat': {'裕汇21508': [(0, 0), (110.0, 19.2)],
   '聚龙988': [(110.0, 0), (88.0, 14.0)],
   '豫信货17799': [(110.0, 14.0), (110.0, 17.0)]},
  'best_use_rate': 0.5476890756302522},
 14: {'brake_boat': {'民超': [(0, 0), (107.0, 17.24)],
   '乔泰26': [(107.0, 0), (110.0, 19.2)]},
  'best_use_rate': 0.41561764705882354},
 15: {'brake_boat': {'江集运1212': [(0, 0), (105.0, 17.24)],
   '渝扬6': [(105.0, 0), (106.0, 17.25)]},
  'best_use_rate': 0.3822163865546218},
 16: {'brake_boat': {'远洋9210': [(0, 0), (100.0, 17.2)]},
  'best_use_rate': 0.18067226890756302}}

In [367]:
ind_series=all_brake_boat_new.keys()
all_brake_boat_new_series=all_brake_boat_new.values()

In [368]:
res_df=pd.DataFrame(all_brake_boat_new_series)
res_df=res_df.sort_values(by='best_use_rate',ascending=False)

In [369]:
# help(res_df.sort_values)

In [370]:
res_df.head()

                                          brake_boat  best_use_rate
0  {'千千988': [(0, 0), (99.6, 16.23)], '海牛1009': [...       0.848062
1  {'鄂石2176': [(0, 0), (86.8, 14.83)], '长兴1868': ...       0.834500
2  {'砚海998': [(0, 0), (92.0, 14.83)], '恒洋18': [(0...       0.813751
3  {'飞艳18': [(0, 0), (92.0, 14.83)], '江韵1008': [(...       0.801518
4  {'江泓898': [(0, 0), (99.8, 16.25)], '领航飞翔': [(0...       0.798507

In [371]:
##保存结果修改文件名称
# res_df.to_excel('{}.xlsx'.format('data_529'),index=False)

In [372]:
res_df.head(1)['brake_boat']

0    {'千千988': [(0, 0), (99.6, 16.23)], '海牛1009': [...
Name: brake_boat, dtype: object

In [373]:
def process_res(row):
    print(row)
#      name_all=[]
#      name_list=list(row.keys())
   
#             name_all.extend(name_list)
    name_all=[]
    for k,v in row.items():
        name_all.append(k)
        
        v_size_str=(str(v[1][0]),str(v[1][1]))
        vs=','.join(v_size_str)    
        name_all.append(vs)
    if len(row)<6:
        dif_num=2*(6-len(row))
        name_all.extend(['']*dif_num)
    return pd.Series(name_all)

In [374]:
'name1','size1'

('name1', 'size1')

In [375]:
alls=[]
for i in range(12):
    alls.append('name{}'.format(i+1))
    alls.append('size{}'.format(i+1))

In [376]:
print(alls)

['name1', 'size1', 'name2', 'size2', 'name3', 'size3', 'name4', 'size4', 'name5', 'size5', 'name6', 'size6', 'name7', 'size7', 'name8', 'size8', 'name9', 'size9', 'name10', 'size10', 'name11', 'size11', 'name12', 'size12']

In [377]:
res_df.shape

(17, 2)

In [378]:
# res_df[alls]=
aa=res_df['brake_boat'].apply(lambda x:process_res(x))

{'千千988': [(0, 0), (99.6, 16.23)], '海牛1009': [(0, 16.23), (129.92, 16.24)], '宜都广翼196': [(99.6, 0), (78.0, 13.63)], '海牛69': [(129.92, 16.23), (130.0, 16.0)], '宏青818': [(177.6, 0), (86.0, 14.0)]}
{'鄂石2176': [(0, 0), (86.8, 14.83)], '长兴1868': [(0, 14.83), (129.98, 16.26)], '龙昊1005': [(129.98, 14.83), (129.97, 16.2)], '宜化6号': [(86.8, 0), (82.0, 14.0)], '新平江3003': [(168.8, 0), (87.0, 14.83)]}
{'砚海998': [(0, 0), (92.0, 14.83)], '恒洋18': [(0, 14.83), (130.0, 16.0)], '镔港808': [(130.0, 14.83), (110.0, 17.2)], '永通6': [(92.0, 0), (87.0, 14.0)], '云隆88': [(179.0, 0), (85.0, 14.03)]}
{'飞艳18': [(0, 0), (92.0, 14.83)], '江韵1008': [(0, 14.83), (79.6, 13.62)], '云浩818': [(79.6, 14.83), (75.7, 13.12)], '平洋898': [(155.3, 14.83), (105.0, 17.2)], '川北988': [(92.0, 0), (86.48, 14.24)], '长安69': [(178.48000000000002, 0), (82.0, 14.04)]}
{'江泓898': [(0, 0), (99.8, 16.25)], '领航飞翔': [(0, 16.25), (79.8, 13.6)], '新平江1028': [(79.8, 16.25), (87.0, 13.62)], '云浩918': [(99.8, 0), (74.3, 13.64)], '航兴901': [(166.8, 16.25), (86.8, 16.23)], '新平江3005': [(174.1, 0), (87.0, 14.8)]}
{'龙腾819': [(0, 0), (90.0, 15.0)], '长荣998': [(0, 15.0), (110.0, 17.0)], '豫宛货2077': [(90.0, 0), (79.6, 13.6)], '长航集运0335': [(110.0, 15.0), (107.0, 17.24)], '九五888': [(169.6, 0), (92.0, 14.85)]}
{'曙光668': [(0, 0), (85.32, 14.16)], '海辉307': [(0, 14.16), (110.0, 18.0)], '云浩999': [(85.32, 0), (87.0, 14.0)], '豫信货17788': [(110.0, 14.16), (110.0, 17.0)], '新平江1009': [(172.32, 0), (87.0, 13.6)]}
{'天畅908': [(0, 0), (90.8, 14.84)], '金海168': [(0, 14.84), (108.0, 17.2)], '港盛1618': [(108.0, 14.84), (108.0, 17.25)], '曙光888': [(90.8, 0), (79.58, 13.8)], '天龙贰号': [(170.38, 0), (86.0, 14.0)]}
{'浩航1009': [(0, 0), (110.0, 16.0)], '盛畅8198': [(0, 16.0), (79.6, 13.63)], '新宜超越': [(79.6, 16.0), (79.0, 13.0)], '豫信货13986': [(158.6, 16.0), (105.0, 16.24)], '林瑞9': [(110.0, 0), (105.0, 16.0)]}
{'长兴1015': [(0, 0), (104.81, 16.23)], '金河18': [(0, 16.23), (65.5, 10.83)], '吉耘918': [(65.5, 16.23), (99.8, 16.25)], '航平906': [(104.81, 0), (105.0, 16.0)], '和海66': [(165.3, 16.23), (95.0, 16.23)]}
{'祥牛6': [(0, 0), (99.8, 16.3)], '鹏杰8': [(0, 16.3), (105.0, 16.0)], '渝山988': [(99.8, 0), (106.8, 16.25)], '帝豪8': [(105.0, 16.3), (99.9, 16.24)]}
{'宏源819': [(0, 0), (99.8, 16.21)], '浦航998': [(0, 16.21), (99.8, 16.24)], '兴晟05': [(99.8, 0), (99.8, 16.25)], '宏河918': [(99.8, 16.25), (99.8, 16.25)]}
{'宜昌金航66': [(0, 0), (100.0, 16.0)], '国祥898': [(100.0, 0), (110.0, 19.25)], '民联908': [(0, 16.0), (99.6, 16.24)]}
{'裕汇21508': [(0, 0), (110.0, 19.2)], '聚龙988': [(110.0, 0), (88.0, 14.0)], '豫信货17799': [(110.0, 14.0), (110.0, 17.0)]}
{'民超': [(0, 0), (107.0, 17.24)], '乔泰26': [(107.0, 0), (110.0, 19.2)]}
{'江集运1212': [(0, 0), (105.0, 17.24)], '渝扬6': [(105.0, 0), (106.0, 17.25)]}
{'远洋9210': [(0, 0), (100.0, 17.2)]}

In [382]:
aa.shape

(17, 12)

In [383]:
aa.sample(12)

,0,1,2,3,4,5,6,7,8,9,10,11
4,江泓898,"99.8,16.25",领航飞翔,"79.8,13.6",新平江1028,"87.0,13.62",云浩918,"74.3,13.64",航兴901,"86.8,16.23",新平江3005,"87.0,14.8"
12,宜昌金航66,"100.0,16.0",国祥898,"110.0,19.25",民联908,"99.6,16.24",,,,,,
16,远洋9210,"100.0,17.2",,,,,,,,,,
5,龙腾819,"90.0,15.0",长荣998,"110.0,17.0",豫宛货2077,"79.6,13.6",长航集运0335,"107.0,17.24",九五888,"92.0,14.85",,
1,鄂石2176,"86.8,14.83",长兴1868,"129.98,16.26",龙昊1005,"129.97,16.2",宜化6号,"82.0,14.0",新平江3003,"87.0,14.83",,
9,浩航1009,"110.0,16.0",盛畅8198,"79.6,13.63",新宜超越,"79.0,13.0",豫信货13986,"105.0,16.24",林瑞9,"105.0,16.0",,
8,长兴1015,"104.81,16.23",金河18,"65.5,10.83",吉耘918,"99.8,16.25",航平906,"105.0,16.0",和海66,"95.0,16.23",,
7,曙光668,"85.32,14.16",海辉307,"110.0,18.0",云浩999,"87.0,14.0",豫信货17788,"110.0,17.0",新平江1009,"87.0,13.6",,
14,民超,"107.0,17.24",乔泰26,"110.0,19.2",,,,,,,,
2,砚海998,"92.0,14.83",恒洋18,"130.0,16.0",镔港808,"110.0,17.2",永通6,"87.0,14.0",云隆88,"85.0,14.03",,
0,千千988,"99.6,16.23",海牛1009,"129.92,16.24",宜都广翼196,"78.0,13.63",海牛69,"130.0,16.0",宏青818,"86.0,14.0",,
11,宏源819,"99.8,16.21",浦航998,"99.8,16.24",兴晟05,"99.8,16.25",宏河918,"99.8,16.25",,,,

In [384]:
aa['best_use_rate']=res_df['best_use_rate']

In [385]:
aa.head()

,0,1,2,3,4,5,6,7,8,9,10,11,best_use_rate
0,千千988,"99.6,16.23",海牛1009,"129.92,16.24",宜都广翼196,"78.0,13.63",海牛69,"130.0,16.0",宏青818,"86.0,14.0",,,0.848062
1,鄂石2176,"86.8,14.83",长兴1868,"129.98,16.26",龙昊1005,"129.97,16.2",宜化6号,"82.0,14.0",新平江3003,"87.0,14.83",,,0.834500
2,砚海998,"92.0,14.83",恒洋18,"130.0,16.0",镔港808,"110.0,17.2",永通6,"87.0,14.0",云隆88,"85.0,14.03",,,0.813751
3,飞艳18,"92.0,14.83",江韵1008,"79.6,13.62",云浩818,"75.7,13.12",平洋898,"105.0,17.2",川北988,"86.48,14.24",长安69,"82.0,14.04",0.801518
4,江泓898,"99.8,16.25",领航飞翔,"79.8,13.6",新平江1028,"87.0,13.62",云浩918,"74.3,13.64",航兴901,"86.8,16.23",新平江3005,"87.0,14.8",0.798507

In [386]:
columns=['best_use_rate',0,1,2,3,4,5,6,7,8,9,10,11]
aa.to_excel('{}.xlsx'.format('data_final_scheduled_sheet3'),index=False,columns=columns)

In [1]:
import os
file_path = "E:/tt/abc.py"
filepath,fullflname = os.path.split(file_path)
fname,ext = os.path.splitext(fullflname)

In [2]:
filepath,fullflname

('E:/tt', 'abc.py')

In [3]:
fname,ext

('abc', '.py')

In [3]:
d_p='sheet_all.xlsx'

In [2]:
import pandas as pd

In [7]:
df=pd.read_excel(d_p,header=None)

In [8]:
df.head()

         0              1
0  江海洋2016   92.00, 16.20
1    航万968  104.98, 16.23
2    灏泽001  105.00, 16.23
3   长兴1668  129.98, 16.26
4    镔港968  108.00, 17.25

In [10]:
import re

In [12]:
df[['L','W']]=df[1].apply(lambda x:process_data(x))

In [13]:
df.head()

         0              1       L       W
0  江海洋2016   92.00, 16.20   92.00   16.20
1    航万968  104.98, 16.23  104.98   16.23
2    灏泽001  105.00, 16.23  105.00   16.23
3   长兴1668  129.98, 16.26  129.98   16.26
4    镔港968  108.00, 17.25  108.00   17.25

In [19]:
df['W']=df['W'].astype('float')

In [22]:
df=df.sort_values(by='W',ascending=False)

In [24]:
df_w=df[df['W']>=16]

In [25]:
df_w.to_excel('w_16_more.xlsx',index=None)